services:
  painthelper:
    build: .
    ports:
      - 8080:8080
    environment:
      DB_USER_PASSWD: ${DB_USER_PASSWD}
      DB_CONNECTION_STRING: jdbc:mariadb://database:3306/knzoon
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  database:
    image: mariadb:10.11
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD}
      MYSQL_DATABASE: knzoon
      MYSQL_USER: knzoonApp
      MYSQL_PASSWORD: ${DB_USER_PASSWD}
    volumes:
      - db-volume:/var/lib/mysql
      - ./dll/setup_database.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

volumes:
  db-volume: